name: Apple Certificate Action
description: Installing an Apple certificate on macOS runners for Xcode development
author: Nicholas Wong
branding:
  icon: anchor
  color: orange
inputs:
  build-certificate-base64:
    description: Your Apple signing certificate in p12 format and base64 encoded
    required: true
  p12-password:
    description: The password for your Apple signing certificate
    required: true
  build-provision-profile-base64:
    description: Your Apple provisioning profile what is base64 encoded
    required: true
  keychain-password:
    description: A password for the keychain to be created on the runner
    required: true
runs:
  using: "composite"
  steps:
    - name: Install the Apple certificate and provisioning profile
      shell: bash
      env:
        BUILD_CERTIFICATE_BASE64: ${{ inputs.build-certificate-base64 }}
        P12_PASSWORD: ${{ inputs.p12-password }}
        BUILD_PROVISION_PROFILE_BASE64: ${{ inputs.build-provision-profile-base64 }}
        KEYCHAIN_PASSWORD: ${{ inputs.keychain-password }}
      run: |
        # create variables
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

        # import certificate and provisioning profile from secrets
        echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
        echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

        # create temporary keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

        # import certificate to keychain
        security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH

        # apply provisioning profile
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles