name: Testing workflow
on: [push, pull_request, workflow_dispatch]
jobs:
  run:
    runs-on: macos-latest
    steps:
      - name: testing
        uses: ./
        with:
          build-certificate-base64: ${{ secrets.IOS_BUILD_CERTIFICATE_P12_BASE64 }}
          p12-password: ${{ secrets.IOS_BUILD_CERTIFICATE_P12_PASSWORD }}
          build-provision-profile-base64: ${{ secrets.IOS_BUILD_PROVISION_PROFILE_BASE64 }}
          keychain-password: ${{ secrets.MAC_MACHINE_KEYCHAIN_PASSWORD }}